print("BMI CALCULATOR")
height=input("ENTER YOUR HEIGHT: \n")
weight=input("ENTER YOUR WEIGHT: \n")
weight_as_int=int(weight)
height_as_int=float(height)
bmi=weight_as_int/(height_as_int*height_as_int)
print("BMI of the person is:",bmi)
print("DIGITS OF FIRST 2 NUMBERS")
two_dig_number=input("Enter a two digit number: \n")
# print(type(two_dig_number))
firstDig=int(two_dig_number[0])
secondDig=int(two_dig_number[1])
sum=firstDig+secondDig
print(sum)